### ISSUE TITLE
Badge Request

### ISSUE THREAD

**Issue by omxpro** [wingio/BadgeDB#12]
### Discord ID

248470317540966443

### Drawable Name

ic_profile_badge_certified_moderator_32dp | ic_profile_badge_premium_guild_subscription_lvl9_32dp | ic_profile_badge_partner_32dp | ic_staff_badge_blurple_24dp |  ic_verified_badge_banner | ic_account_github

### Toast Message

Discord Moderator | Discord Nitro | Discord Partner | Verified Youtuber | omxpro

**Comment by wingio** [comment]
Invalid user id

**Comment by omxpro** [comment]
248470317540966443
