### ISSUE TITLE
Badge Request

### ISSUE THREAD

**Issue by HypedDomi** [wingio/BadgeDB#5]
### Discord ID

354191516979429376

### Drawable Name

img_logo

### Toast Message

Created at: 04.09.2017

**Comment by HypedDomi** [comment]
### Drawable Name
ic_verified_badge_banner

### Toast Message
Birthday: 17.11.2003

**Comment by HypedDomi** [comment]
### Drawable Name
icon_flag_de

### Toast Message
Germany

**Comment by wingio** [comment]
Added

**Comment by HypedDomi** [comment]
The toast for `img_logo` is wrong. Could you update it to `Created at: 04.09.2017`?
